---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Introduction to R
================

### Moffitt Cancer Center 

-----

:calendar: Wednesday June 9 - July 14, 2021

:alarm_clock: 3-4 pm

:office: via Zoom (link coming soon)

:computer: [Moffitt](https://moffitt.org/)

-----

## Setup

The course will be hosted through ....

<!-- 
* When you're done, put a green post-it on your computer. 
* If you need help, put up a pink post-it.
-->

## Slides

<!--
* Rewrite as links to slides on github once they are made
* [Name of talk](path/to/slides.pdf)
-->

* Introduction and R and Rmarkdown
* Data Manipulation I and II
* Visualization with ggplot
* Statistical testing
* Best practices

## Code

Find our live coded notes in [`notes/`](notes/) as we commit them.

## Questions?

Feel free to ask questions in the [GitHub Issues](https://github.com).

## Overview

This is a 6 week course designed to introduce future users to R and Rstudio.
We will cover data cleaning using the `tidyverse`, creating visuals with `ggplot`,
basic statistical analysis and writing documents with `Rmarkdown`. In the end 
you should be able to: 

<!--
Each instructor should provide a one sentence summary of what participants
will be able to do after thier lecture 
-->

* import and manipulate data into different formats
* create new variables and recode existing ones 
* plot data using the appropriate figure type 
* perform basic statistics
* write Rmarkdown reports

## Who is this course designed for?

Have you never written any code in R or any other programming language? Are you
familiar with R, but hoping to bulk up your basic skills? Have you used R but are
new to the `tidyverse` framework? 

## Learning objectives

Introduction to R/Rstudio and Rmarkdown

  - Get familiar with the R and Rstudio environment
  - Understand basic R code structure (packages, data structures)
  - Create and render `Rmarkdown` documents in multiple formats 
    
Data import and manipulation - Part I

  - Import various data types 
  - Explain the fundamentals of "tidy data" and the `tidyverse`
  - Clean data sets using `dplyr` verbs
    
Data manipulation and cleaning - Part II

  - Merge data sets
  - Transform data  
    
Visualization 

  - Understand the principles of `ggplot2`
  - Determine appropriate visualizations 
  - Plot - `geom_smooth` to see a model over the data 
    
Basic statistics 

  - ttest, correlation and chisq 
  - Model data 
  - Report findings from R output 
    
Final coding project 

  - Organize projects and name objects in a uniform manner
  - Create a reproducible workflow
  - Setting up your own R installation 

## Materials/RStudio Cloud

Materials will be made available on [GitHub](https://github.com/FridleyLab/Introduction-to-R/).  If you are using an organization-issued laptop, you may want to verify before you arrive that you can access GitHub.

In this course, we will be using a version of RStudio available online. The class
workspace can be accessed [here](https://rstudio.cloud/spaces/146648/join?access_code=lwgMkLa2E%2BSSKGUFRhilRqgJW1lz7OCF9pZVjhxf). Please create a user account before the first day of class 
(or connect with either a GitHub account or Google account). 

## Schedule and Links

*   June 09 - `rmarkdown`
    * [Zoom link](https://moffitt.zoom.us/j/95042034701)
*   June 16 - Data import and wrangling part I
    * [Zoom link](https://moffitt.zoom.us/j/99077101114)
*   June 23 - Data import and wrangling part II
    * [Zoom link](https://moffitt.zoom.us/j/92170925460)
*   June 30 - Visualizations with `ggplot2`
    * [Zoom link](https://moffitt.zoom.us/j/96225512559)
*   July 07 - Basic statistics
    * [Zoom link](https://moffitt.zoom.us/j/91931267792)
*   July 17 - Best practices 
    * [Zoom link](https://moffitt.zoom.us/j/96050438861)

## Instructors

<!--
Add links to personal websites and double check personal info
* add small blurbs/pictures for each instructor? 
-->

This course is taught by members of Moffitt staff including Jordan
Creed, a data analyst in the Department of Health Informatics, Zachary
Thompson and Ram Thappa, biostatisticians in the Bioinformatics and
Biostatistics Core.

-----
